[server_config]
bind_address = "127.0.0.1:8080" # Optional in TOML, can be overridden by env var `VSS_BIND_ADDRESS`

# Uncomment the table below to verify JWT tokens in the HTTP Authorization header against the given RSA public key,
# can be overridden by env var `VSS_JWT_RSA_PEM`
# [jwt_auth_config]
# rsa_pem = """
# -----BEGIN PUBLIC KEY-----
# -----END PUBLIC KEY-----
# """

[postgresql_config]
username = "postgres"          # Optional in TOML, can be overridden by env var `VSS_PSQL_USERNAME`
password = "postgres"          # Optional in TOML, can be overridden by env var `VSS_PSQL_PASSWORD`
address = "127.0.0.1:5432"     # Optional in TOML, can be overridden by env var `VSS_PSQL_ADDRESS`
# We first connect to `default_database` to create `vss_database` if it does not exist
default_database = "postgres"  # Optional in TOML, can be overridden by env var `VSS_PSQL_DEFAULT_DB`
vss_database = "vss"           # Optional in TOML, can be overridden by env var `VSS_PSQL_VSS_DB`

# [postgresql_config.tls]  # Uncomment, or set env var `VSS_PSQL_TLS` to make TLS connections to the postgres database
#
# Uncomment the lines below, or set `VSS_PSQL_CRT_PEM` to add a root certificate to your trusted root certificates
#
# crt_pem = """
# -----BEGIN CERTIFICATE-----
# -----END CERTIFICATE-----
# """

# [log_config]
# level = "debug"    # Uncomment, or set env var `VSS_LOG_LEVEL` to set the log level, the default is "debug"
# file = "vss.log"   # Uncomment, or set env var `VSS_LOG_FILE` to set the log file path, the default is "vss.log"
