[server_config]
host = "127.0.0.1"
port = 8080
# rsa_pub_file_path = "rsa_public_key.pem" # Uncomment to verify JWT tokens in the HTTP Authorization header

[postgresql_config]
username = "postgres"  # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_USERNAME`
password = "postgres"  # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_PASSWORD`
host = "localhost"
port = 5432
default_database = "postgres"
vss_database = "vss"
# tls = { }                        # Uncomment to make TLS connections to the postgres database using your machine's PKI
# tls = { ca_file = "ca.pem" }     # Uncomment to make TLS connections to the postgres database with an additional root certificate
