[server_config]
host = "127.0.0.1"
port = 8080

# Uncomment the table below to verify JWT tokens in the HTTP Authorization header against the given RSA public key,
# can be overridden by env var `VSS_JWT_RSA_PEM`
# [jwt_auth_config]
# rsa_pem = """
# -----BEGIN PUBLIC KEY-----
# -----END PUBLIC KEY-----
# """

[postgresql_config]
username = "postgres"  # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_USERNAME`
password = "postgres"  # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_PASSWORD`
host = "localhost"
port = 5432
# We first connect to `default_database` to create `vss_database` if it does not exist
default_database = "postgres"
vss_database = "vss"

# [postgresql_config.tls]  # Uncomment to make TLS connections to the postgres database
#
# Uncomment the lines below to add a root certificate to your trusted root certificates
#
# crt_pem = """
# -----BEGIN CERTIFICATE-----
# -----END CERTIFICATE-----
# """
